Repository UMC-GetIT/GetIT-android, pull requests merged in 2022-08, with the labels that each got.

#45 feat/7 mainview
  GetIT/app/src/main/java/com/getit/getit/ui/BaseActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/BaseFragment.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/MainActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/comparison/ComparisonFragment.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/HomeFragment.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/TermRVAdapter.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/data/ItTermIcon.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/MypageFragment.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/search/SearchFragment.kt
  GetIT/app/src/main/res/drawable/editText_box.png
  GetIT/app/src/main/res/drawable/google_login.png
  GetIT/app/src/main/res/drawable/naver_login.png
  GetIT/app/src/main/res/drawable/page_num_bg.png
  GetIT/app/src/main/res/drawable/recommend_button_bg.png
  GetIT/app/src/main/res/layout/fragment_home.xml
  GetIT/app/src/main/res/layout/item_itterm.xml
  GetIT/app/src/main/res/values/colors.xml
Labels: feat

#62 feat/33 recommend products view
  GetIT/app/build.gradle
  GetIT/app/src/main/AndroidManifest.xml
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/HomeFragment.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/WindowActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/data/RecommendQuestion.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/recommend/RecommendActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/recommend/RecommendAnswerRVAdapter.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/recommend/RecommendQuestionActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/recommend/RecommendQuestionRVAdapter.kt
  GetIT/app/src/main/res/drawable/ic_close.xml
  GetIT/app/src/main/res/layout/activity_recommend.xml
  GetIT/app/src/main/res/layout/activity_recommend_question.xml
  GetIT/app/src/main/res/layout/activity_signup.xml
  GetIT/app/src/main/res/layout/activity_window.xml
  GetIT/app/src/main/res/layout/comparison_result.xml
  GetIT/app/src/main/res/layout/fragment_home.xml
  GetIT/app/src/main/res/layout/item_recommend_answer.xml
  GetIT/app/src/main/res/layout/item_recommend_question.xml
  GetIT/app/src/main/res/layout/toolbar_main.xml
  GetIT/app/src/main/res/layout/toolbar_window.xml
Labels: feat

#67 UPDATE/ retrofit, shared preference 하나로 통일
  GetIT/app/src/main/AndroidManifest.xml
  GetIT/app/src/main/java/com/getit/getit/config/XAccessTokenInterceptor.kt
  GetIT/app/src/main/java/com/getit/getit/ui/login/LoginActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/login/LoginView.kt
  GetIT/app/src/main/java/com/getit/getit/ui/login/SignUpActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/login/SignUpView.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/MainActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/server/AuthResponse.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/server/AuthRetrofitInterface.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/server/AuthService.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/MypageFragment.kt
  GetIT/app/src/main/java/com/getit/getit/utils/ApplicationClass.kt
  GetIT/app/src/main/java/com/getit/getit/utils/SharedPreferencesManager.kt
Labels: update

#77 update/57-리뷰 더보기 추가
  GetIT/.idea/deploymentTargetDropDown.xml
  GetIT/.idea/misc.xml
  GetIT/app/build.gradle
  GetIT/app/src/main/AndroidManifest.xml
  GetIT/app/src/main/java/com/getit/getit/ui/BaseActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/MypageFragment.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/MypageLikeRV.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/MypageReviewRV.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/UserInfo.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/like/LikeApiService.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/like/LikeProductAcitivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/like/LikeProducts.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/like/LikeRVAdatper.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/review/DeleteReview.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/review/ReviewApiService.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/review/ReviewDeleteActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/review/ReviewProductAcitivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/review/ReviewProducts.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/review/ReviewpdRVAdapter.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/settings/ChangeProfileActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/settings/DeveloperInfoActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/settings/PreferenceHelper.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/settings/SharedManager.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/settings/changeProfile/ChangeProfileApi.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/settings/changeProfile/ProfileRetrofit.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/settings/changeProfile/newprofile.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/settings/changeProfile/profile.kt
  GetIT/app/src/main/java/com/getit/getit/utils/ApplicationClass.kt
  GetIT/app/src/main/java/com/getit/getit/utils/SharedPreferencesManager.kt
  GetIT/app/src/main/res/drawable/ic_delete_review.xml
  GetIT/app/src/main/res/layout/activity_mypage_like_list.xml
  GetIT/app/src/main/res/layout/activity_mypage_review_list.xml
  GetIT/app/src/main/res/layout/change_privacy.xml
  GetIT/app/src/main/res/layout/fragment_mypage.xml
  GetIT/app/src/main/res/layout/item_mypage_likelist.xml
  GetIT/app/src/main/res/layout/item_mypage_product_like.xml
  GetIT/app/src/main/res/layout/item_mypage_product_review.xml
  GetIT/app/src/main/res/layout/mypage_product_review.xml
  GetIT/app/src/main/res/layout/setting_change_privacy.xml
  GetIT/app/src/main/res/layout/setting_change_profile.xml
  GetIT/app/src/main/res/layout/setting_developer_info.xml
Labels: jennifer, feat

#78 Feat/48 category seach fucntion
  GetIT/.idea/misc.xml
  GetIT/app/src/main/java/com/getit/getit/ui/main/category/CategoryResponse.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/category/CategoryRetrofitInterface.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/category/CategoryService.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/category/SearchFragment.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/category/SearchRVAdapter.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/category/detail/InformationRVAdapter.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/category/detail/ProductDetailActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/category/detail/ProductDetailResponse.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/category/detail/ProductDetailView.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/category/detail/SideImageRVAdapter.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/settings/SettingActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/searchproduct/SearchProductRVAdapter.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/searchproduct/SearchProductResponse.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/searchproduct/SearchResultActivity.kt
  GetIT/app/src/main/res/layout/activity_product_detail.xml
  GetIT/app/src/main/res/layout/item_detail_information.xml
  GetIT/app/src/main/res/layout/item_product_detail_image.xml
  GetIT/app/src/main/res/layout/item_search.xml
Labels: feat, yuja

#81 Feat/33 recommend product
  GetIT/.idea/misc.xml
  GetIT/app/src/main/AndroidManifest.xml
  GetIT/app/src/main/java/com/getit/getit/data/NameImagePriceProduct.kt
  GetIT/app/src/main/java/com/getit/getit/data/Products.kt
  GetIT/app/src/main/java/com/getit/getit/ui/login/LoginActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/login/SignUpActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/login/server/AuthService.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/category/SearchFragment.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/category/detail/ProductDetailActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/comparison/CompareAfterActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/HomeFragment.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/data/RecommendAnswerSet.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/recommend/GetRecommendQuestionSet.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/recommend/RecommendActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/recommend/RecommendAnswerRVAdapter.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/recommend/RecommendProductsQuestionActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/recommend/RecommendProductsView.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/recommend/RecommendQuestionActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/recommend/RecommendQuestionRVAdapter.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/recommend/RecommendResultActivity.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/recommend/RecommendResultRVAdapter.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/server/MainRecommendService.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/server/RecommendProductsService.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/server/RecommendResponse.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/home/server/RecommendRetrofitInterface.kt
  GetIT/app/src/main/java/com/getit/getit/ui/main/mypage/settings/ChangePrivacyActivity.kt
  GetIT/app/src/main/res/color/color_chip_background.xml
  GetIT/app/src/main/res/color/color_chip_text.xml
  GetIT/app/src/main/res/drawable/gram_360.png
  GetIT/app/src/main/res/drawable/samsung.png
  GetIT/app/src/main/res/drawable/style_summit_button_off.xml
  GetIT/app/src/main/res/drawable/style_summit_button_on.xml
  GetIT/app/src/main/res/layout/activity_comparison_after.xml
  GetIT/app/src/main/res/layout/activity_recommend_question.xml
  GetIT/app/src/main/res/layout/activity_recommend_result.xml
  GetIT/app/src/main/res/layout/activity_search.xml
  GetIT/app/src/main/res/layout/item_compare_answer.xml
  GetIT/app/src/main/res/layout/item_recommend_answer.xml
  GetIT/app/src/main/res/layout/item_recommend_product.xml
  GetIT/app/src/main/res/layout/item_recommend_question.xml
  GetIT/app/src/main/res/values-night/themes.xml
  GetIT/app/src/main/res/values/themes.xml
Labels: feat, rose
